OBJS = CleanUpTheWords.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

CleanUpTheWords : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o CleanUpTheWords

CleanUpTheWords.o : CleanUpTheWords.cpp
			 $(CC) $(CFLAGS) CleanUpTheWords.cpp
			 
clean:
	\rm *.o *~ CleanUpTheWords